#!/usr/bin/expect -f
set command1 [lindex $argv 0]
set command2 [lindex $argv 1]
set psw [lindex $argv 2]
set timeout [lindex $argv 3]
spawn  scp -r $command1 $command2

expect {
	"yes/no" { send "yes\r"; exp_continue}

    "*assword:" { send "$psw\r" }
}
expect eof
