#!/usr/bin/expect -f
set command [lindex $argv 0]
set psw [lindex $argv 1]
set command2 [lindex $argv 2]
spawn  ssh $command
set timeout 120
expect {
	"yes/no" { send "yes\r"; exp_continue}
    "*assword:" { send "$psw\r" }
}

expect "WIKS*"
send "sh $command2\r"

expect {
    -re "tar" {
        exit
    }
    -re "csv" {
        exit
    }
    -re "Error" {
        exit
    }
}
expect eof
