#!/usr/bin/expect -f
set command [lindex $argv 0]
set psw [lindex $argv 1]
set pic [lindex $argv 2]
spawn  ssh $command

expect {
	"yes/no" { send "yes\r"; exp_continue}
    "*assword:" { send "$psw\r" }
}

expect "WIKS*"
send "screencapture -C $pic\r"
expect eof
